# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37346ce0adebb0e5880bb434004ecc6dfda2a3d7aaa39d581d54101e6acbf99bd9c51cbf7eb7c54150bec9b4bd2ad8937bc8641484cb192cd4b243cdf3a0d80a

test:
  secret_key_base: a4b97334df50a69007246be69e7c894dd5fbbe08847bad02d9ecdac4d9c9f854af1a7dd246e528d6b8e194806467608b62528bd8e7b895f3f97a99cdf7e9e0f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
